# Generated by Django 4.2.6 on 2023-10-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasebox',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
