# Generated by Django 4.2.6 on 2023-10-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebox', '0002_alter_phrasebox_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasebox',
            name='translation',
            field=models.CharField(default='', max_length=255),
        ),
    ]
