# Generated by Django 4.2.6 on 2023-10-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebox', '0003_phrasebox_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasebox',
            name='audio_file',
            field=models.FileField(default='default_audio_file.mp3', upload_to='audio/'),
        ),
    ]
